### ISSUE TITLE
empty departement folders

### ISSUE THREAD

**Issue by Bazdm** [wblondel/PagesJaunes-Scraper#11]
Hello wblondel !

Is the script still working ? nothing can be found inside the folders.

Many thanks for the work

**Comment by wblondel** [comment]
Hi!

You are welcome :)

Did you see any error during the execution of the script?
I will check that later.

William

**Comment by wblondel** [comment]
Hi again,

I tested the script with the department 79 (Deux-Sèvres) and it worked well.

Which directory did you try to download (PagesBlanches / PagesJaunes, and department number) ? Maybe it doesn't exist anymore on the PagesBlanches / PagesJaunes website.

William

**Comment by Bazdm** [comment]
Hi William,

Tanks for coming back to me, I try it on 75 (all of them) and 92 (all of them) and the program immediately close after showing the “mesadresses” link 
 Thanks 

Bazilio

**Comment by wblondel** [comment]
I am sorry to inform you that all the directories (both the printed version and the online version) of these departments don't exist anymore:
06, 13, 20, 30, 31, 33, 34, 38, 42, 44, 49, 57, 59, 60, 62, 64, 69, 74, 75, 76, 77, 78, 83, 84, 91, 92, 93, 94, 95, 974, 975, 976

Previous years can't be downloaded neither.

A warning is shown when you start the program, but in French only. I'll translate it into English also.
